export default [
  {
    login: "ThaELL1",
    id: 37319124,
    node_id: "MDQ6VXNlcjM3MzE5MTI0",
    avatar_url: "https://avatars3.githubusercontent.com/u/37319124?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ThaELL1",
    html_url: "https://github.com/ThaELL1",
    followers_url: "https://api.github.com/users/ThaELL1/followers",
    following_url:
      "https://api.github.com/users/ThaELL1/following{/other_user}",
    gists_url: "https://api.github.com/users/ThaELL1/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ThaELL1/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ThaELL1/subscriptions",
    organizations_url: "https://api.github.com/users/ThaELL1/orgs",
    repos_url: "https://api.github.com/users/ThaELL1/repos",
    events_url: "https://api.github.com/users/ThaELL1/events{/privacy}",
    received_events_url: "https://api.github.com/users/ThaELL1/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "degreeck",
    id: 31404082,
    node_id: "MDQ6VXNlcjMxNDA0MDgy",
    avatar_url: "https://avatars1.githubusercontent.com/u/31404082?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/degreeck",
    html_url: "https://github.com/degreeck",
    followers_url: "https://api.github.com/users/degreeck/followers",
    following_url:
      "https://api.github.com/users/degreeck/following{/other_user}",
    gists_url: "https://api.github.com/users/degreeck/gists{/gist_id}",
    starred_url: "https://api.github.com/users/degreeck/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/degreeck/subscriptions",
    organizations_url: "https://api.github.com/users/degreeck/orgs",
    repos_url: "https://api.github.com/users/degreeck/repos",
    events_url: "https://api.github.com/users/degreeck/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/degreeck/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Kemmy91",
    id: 42711367,
    node_id: "MDQ6VXNlcjQyNzExMzY3",
    avatar_url: "https://avatars2.githubusercontent.com/u/42711367?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Kemmy91",
    html_url: "https://github.com/Kemmy91",
    followers_url: "https://api.github.com/users/Kemmy91/followers",
    following_url:
      "https://api.github.com/users/Kemmy91/following{/other_user}",
    gists_url: "https://api.github.com/users/Kemmy91/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Kemmy91/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Kemmy91/subscriptions",
    organizations_url: "https://api.github.com/users/Kemmy91/orgs",
    repos_url: "https://api.github.com/users/Kemmy91/repos",
    events_url: "https://api.github.com/users/Kemmy91/events{/privacy}",
    received_events_url: "https://api.github.com/users/Kemmy91/received_events",
    type: "User",
    site_admin: false,
  },
];
